- front/nuxt_app/pages/hello.vue
プルリク承認して！！！
- hello -> hello world in hello.vue
> またcommitするよ

- front/nuxt_app/components/BaseCard.vue
- front/nuxt_app/components/LayoutHeader.vue
- front/nuxt_app/components/LayoutTopWrapper.vue
- front/nuxt_app/components/NavigationBar.vue
- front/nuxt_app/pages/index.vue
> edit Header&NavigationBar

- front/nuxt_app/components/ArticleContent.vue
- front/nuxt_app/components/ArticleWrapper.vue
- front/nuxt_app/components/BaseInputImage.vue
- front/nuxt_app/pages/_id.vue
_id.vueのレスポンシブ対応完了+詳細画面をfirebaseからデータ取得して表示完了+file inputボタン作成
> _id.vueのレスポンシブ対応完了+詳細画面をfirebaseからデータ取得して表示完了+file inputボタン作成

- front/nuxt_app/components/BaseButton.vue
- front/nuxt_app/components/LayoutHeader.vue
ボタンコンポーネントを作成しました。
親側から
・ボタンのタイトル
・リンク先
・イベント
を指定することができます。
> create button components

- front/nuxt_app/components/ArticleContent.vue
- front/nuxt_app/components/BaseInputImage.vue
記事作成時のメイン画像をstorageとfirestoreに格納するための値を取得するフォームを作成。
> メイン画像保存機能実装

- front/nuxt_app/components/ArticleContent.vue
- front/nuxt_app/components/ArticleEdit.vue
- front/nuxt_app/pages/login.vue
- front/nuxt_app/pages/signup.vue
- front/nuxt_app/plugins/firebase.js
- firebase.js をちょっと書き換えました　インポート方法が少し変わりました
- editor.jsでimageのアップロードができるようになりました
> maintain firebase and add editorjs image

- front/nuxt_app/components/ArticleContent.vue
- front/nuxt_app/components/BaseInputImage.vue
画像アップロードボタンとプレビューエリアを表示するコンポーネントを作成。
・storageへの保存機能実装済み
・アップロードした画像を親コンポーネントに渡す仕組み実装済み
> 画像アップロード用コンポーネント完成

- front/nuxt_app/components/BaseCard.vue
- front/nuxt_app/components/LayoutHeader.vue
- front/nuxt_app/components/NavigationBar.vue
- front/nuxt_app/pages/index.vue
firebaseの認証状況にあわせて、ヘッダーを書き換え。
ログイン前：
・ログイン
・会員登録
ログイン後：
・マイページ
・新規投稿
> maintain header for firebaseAuth

- front/nuxt_app/components/BaseCard.vue
- front/nuxt_app/pages/index.vue
・詳細ページにドキュメントIdを渡せるようにしました。 e.g. http://localhost:3000/m3AZwi7DxALiUezLHAN6
・ドキュメントのtimeを一覧に表示
・timeを日本時間のyyyy/mm/ddに変換して表示
> maintain index.vue to show date

- front/nuxt_app/components/ArticleEdit.vue
- front/nuxt_app/components/BaseInputImage.vue
- front/nuxt_app/middleware/authCheck.js
- front/nuxt_app/pages/edit/index.vue
- front/nuxt_app/pages/notes.vue
- midllewareにauth判定を追加
　- notes, editはログインしてないとlogin画面に戻されるように変更
- editページにmainImage用のコンポーネント組み込み
- 機能実装するのに不便だったので、notesページにlogout機能できるボタンも入れてます
> add authCheck and maintain edit-page

- front/nuxt_app/components/LogoutButton.vue
- front/nuxt_app/pages/login.vue
- front/nuxt_app/pages/signup.vue
1.ログイン、新規会員後にindexへ遷移する処理を追加
2.ログアウトボタンのコンポーネントを作成
> ログインページを作成

- front/nuxt_app/components/ArticleEdit.vue
- front/nuxt_app/components/BaseCard.vue
- front/nuxt_app/components/NavigationBar.vue
- front/nuxt_app/composable/changeDate.ts
> add design edit.vue

- front/nuxt_app/components/BaseInputImage.vue
- front/nuxt_app/tailwind.config.js
> maintain edit.vue

- front/nuxt_app/components/BaseInputImage.vue
> maintain edit.vue for desktop window

- front/nuxt_app/components/ArticleContent.vue
composableの関数を呼び出して詳細画面の日時を正しく表示
> 詳細画面の日時を正しく表示

- front/nuxt_app/components/ArticleEdit.vue
- front/nuxt_app/components/BaseInputImage.vue
> upload_mainImage

- front/nuxt_app/components/LogoutButton.vue
- front/nuxt_app/pages/login.vue
- front/nuxt_app/pages/notes.vue
- front/nuxt_app/pages/signup.vue
ログアウトボタンを/notesに設定
ログアウト時に / にリダイレクトするように設定
ログイン状態に合わせてloginページの見た目を変更
> set logout button @login.vue

- front/nuxt_app/components/ArticleContent.vue
- front/nuxt_app/components/ArticleEdit.vue
- front/nuxt_app/components/ArticleList.vue
- front/nuxt_app/components/BaseInputImage.vue
edit/_idから保存できるようにしました
コードが汚くなりました
> Fix save in edit

- front/nuxt_app/components/ArticleList.vue
- front/nuxt_app/components/ArticleListWrapper.vue
- front/nuxt_app/composable/changeTime.ts
- front/nuxt_app/pages/notes.vue
ひとまず見た目の修正と記事の公開情報・作成者IDの取得まで。
ユーザーIDで絞るのがまだできてなく。。
whereで＝uidでorderByする方法がうまくいかなかったのでまた後で考えます！
> 公開情報と作成者IDの取得

- front/nuxt_app/components/BaseCard.vue
- front/nuxt_app/pages/index.vue
index.vueを編集
・公開設定（isPublic == true）のものだけを表示
・iconが入っている場合はiconを表示、それ以外の場合はデフォルトを表示
・authorが入っている場合はauthorを表示、それ以外の場合はデフォルトを表示
・likeが入っている場合はlikeを表示、それ以外の場合はデフォルトを表示
> add icon, isPublic, author, like in index.vue

- front/nuxt_app/components/ArticleEdit.vue
> evaluation decided by icons

- front/nuxt_app/components/ArticleEdit.vue
- front/nuxt_app/components/LayoutGoogleMap.vue
> fix edit.vue

- front/nuxt_app/components/ArticleContent.vue
- front/nuxt_app/components/InfoList.vue
詳細ページで無限にいいねできるようにしました。
めっちゃいいねしましょう
気が向いたら反映お願いします
> infinity いいね！

- front/nuxt_app/components/ArticleContent.vue
- front/nuxt_app/pages/login.vue
- front/nuxt_app/pages/profileEdit.vue
> Google_Auth

- front/nuxt_app/components/LinkPreview.vue
- front/nuxt_app/pages/index.vue
> Adding Tabs

- front/nuxt_app/components/LayoutFooter.vue
> Adding Links

- front/nuxt_app/pages/login.vue
google認証追加
googleアカウントの画像も取り込んでるよ！
> google-sign-in

- front/nuxt_app/components/ArticleContent.vue
- 無限いいねを防止しました
-  ログインしてないといいねできません
- マイページが見れない・・・？
> prevent_infinity_Gooooooooooooooooooood!!!!!!!!!!!!!!
